### ISSUE TITLE
FR  show the single dice results (not the sum)

### ISSUE THREAD

**Issue by Cammagno** [javalent/dice-roller#106]
Maybe is already there, but I've not found it.

What I wish will be something as:
`dice:1d6+1d8+2d10|single`
rendering as:
4,5,8,9

OR

`dice:1d6,1d8,2d10`
rendering as:
4,5,17

I know that I can show the formula to somehow see the single results in it, so I understand if this gets low priority (or none at all) :)

**Comment by valentine195** [comment]
This is possible (albeit clunky) at the moment using a table roller. 

```md
| table |
| `dice: 1d6` `dice: 1d10` `dice: 1d10' |
^dice

`dice: [[note^dice]]`
```

**Comment by Cammagno** [comment]
> 
Thanks!

Probably I'm doing it wrong, because it shows nothing for me:
![image](https://user-images.githubusercontent.com/95725064/169037222-c961c345-0469-44fe-9004-889f459d374e.png)

**Comment by Cammagno** [comment]
> This is possible (albeit clunky) at the moment using a table roller.
Thanks for your answer!

This is what I've got:
![image](https://user-images.githubusercontent.com/95725064/169038334-fcab1b2c-7416-4462-9e74-cf2ea4dd6414.png)

**Comment by JYCasalis** [comment]
@Cammagno 

Add `|---|` as the second row of your table to "close" the header and you should be fine !

Or keep clicking and, eventually, the roller will select the second row that contains a dice-roller (when it picks the first row, then it displays nothing as there is no dice-roller in `table`).

I just pushed a PR to support flags in tables, so this will become better since you'll be able to have only one die icon :-)

**Comment by valentine195** [comment]
Whoops my bad thanks!

**Comment by Cammagno** [comment]
> Add `|---|` as the second row of your table to "close" the header and you should be fine !

Stupid me! That was the problem, of course :D
I stupidly copied the code, even though I should know what a table looks like :D

And thanks for your FR, getting rid of those "extra" dice will make it much prettier
