### ISSUE TITLE
Pick a random note from a particular folder

### ISSUE THREAD

**Issue by nununo** [javalent/dice-roller#159]
Hello,

If I understood correctly, it is easy to pick a random note for a given tag. But I would like to do the same with a folder instead of tag. Would it be possible to implement this?

Amazing plugin btw!

Thanks!

**Comment by soticoker** [comment]
hello, 
I agree a great plug-in, 
however I too would like to see this feature implemented!
Thanks

**Comment by sigrunixia** [comment]
@nununo @soticoker 
The reason why it works with tags, links, and notes is because there is something to link for. A folder by itself does not give off an easily linkable presence within obsidian. However, a way around this limitation is to use folder notes, which you could then combine with an existing method such as tags. 

I'll still mark this as a feature request to be evaluated for possible implementation because _it can_ be done, as Dataview grabs folders and its contents. However, it would be helpful to know each of your use cases for this request is.

**Comment by nununo** [comment]
Understood.

My use case: I have a folder called INBOX which holds the notes still not classified. I would like for my daily note to show one of the notes in that folder. The logic being that if shown one random note at a time I'd be more motivated to classify it than if shown the full list.

Thank you!

**Comment by soticoker** [comment]
Hi @sigrunixia ,

My usecase is "exactly" the same scenario as @nununo except my inbox folder is called "Inbox 001".

Many thanks

**Comment by mattBrighto** [comment]
So would that functionality be considered to be implemented, or perhaps should i implement it myself?

**Comment by valentine195** [comment]
You can roll on Dataview queries, so you could do a DV query against the folder.

**Comment by valentine195** [comment]
https://plugins.javalent.com/dice/dataview

@mattBrighto

**Comment by mattBrighto** [comment]
amazing, thanks!

Mateusz Wroński
