### ISSUE TITLE
[Feature Request] Better Dataview Integration: tables and lists

### ISSUE THREAD

**Issue by Feldherren** [javalent/dice-roller#167]
Dataview supports the generation of lists and tables from its own query language, but Dice Roller doesn't seem to be able to work with those, only inline dataview values. Advanced Tables are fine but I need to fill out every entry in that table, and as far as I can tell Advanced Tables doesn't support automatic generation of tables from something like any entry with a tag.

**Comment by sigrunixia** [comment]
@Feldherren 

Further integration of Dataview features is not planned, because Dataview honestly does it better. Instead, Dice Roller has API that can be read by those plugins and used. The specific [calls are here](https://github.com/javalent/dice-roller/blob/master/src/api/api.ts).

Additional API information is found on this [section of the readme](https://github.com/javalent/dice-roller#usage-in-other-plugins) and within the NPM module of the plugin if you fork the repo.
