### ISSUE TITLE
Any expression using parentheses breaks

### ISSUE THREAD

**Issue by mulfok** [javalent/dice-roller#58]
As of 7.8.3, it looks like any dice rolls with parenthesis have stopped working.

Dice usage such as: `dice: 1 + (overall_level - 3)d5` used to produce:

![demonstration](https://user-images.githubusercontent.com/50339059/143134638-2e956863-f451-4963-bd9c-86549394426e.gif)

...it now unfortunately doesn't render anything, and opening any note with expressions like these produce the error message: 

```
There was an error parsing the dice string: dice: 1 + (overall_level - 3)d5

Error: Mismatched Parentheses
```
![image](https://user-images.githubusercontent.com/50339059/143134988-0fc797f0-d064-4117-8165-4996bcc67069.png)

I've tried rearranging the parentheses in every-which-way, but on both my phone and computer, they return the same error message.

This might just be some sillyness on my part, but both the brackets are the same.
Sorry for the trouble haha,,

**Comment by valentine195** [comment]
No worries!

I am actually surprised that this *ever* worked, and if it did. it likely did not work the way you thought it was working behind the scenes. 

I'm not entirely sure I'll be able to implement this, unfortunately, because the entire string is parsed for tokens and then the stack is parsed. Let me give it some though.

**Comment by sigrunixia** [comment]
Much of this functionality was implemented in different ways, through conditionals and text strings. If something more is needed, a new issue can be created.
